twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    date:
        timezone: America/Vancouver
        format: Y-m-d g:i:s A
        interval_format: '%%d days'
    form_themes:
        - 'bootstrap_3_horizontal_layout.html.twig'
        - "@NinesUtil/form/fields.html.twig"
        - '@TetranzSelect2Entity/Form/fields.html.twig'
        - 'jquery.collection.html.twig'
    globals:
        comment_service: '@Nines\FeedbackBundle\Services\CommentService'
        thumb_width: '%pi.thumb_width%'
        thumb_height: '%pi.thumb_height%'
