services:
  db:
    container_name: pi_db
    image: mariadb:10.11
    ports:
      - "13306:3306"
    volumes:
      - .data/mariadb:/var/lib/mysql
      - ./docker/mariadb/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./docker/mariadb/init:/docker-entrypoint-initdb.d
      # # HACK: easy sql script running for setting up db
      # - ./pi.sql:/pi.sql
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: pi
      MARIADB_USER: pi
      MARIADB_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "mysql pi -u pi -ppassword -e 'SELECT 1;'  || exit 1"]
      interval: 2s
      retries: 120

  app:
    container_name: pi_app
    # image: dhil/pi
    build:
      context: .
      target: pi
    ports:
      - "8080:80"
    volumes:
      # code for development
      - .:/var/www/html

      # use the container's var (for cache, etc)
      - /var/www/html/var
      # persist file uploads in .data
      - .data/app/data:/var/www/html/data
      - .data/app/cap_images:/var/www/html/public/images/caps
      # persist logs
      - .data/app/log:/var/www/html/var/log

      # use the container's node_modules & vendor folders (don't override)
      - /var/www/html/public/node_modules
      - /var/www/html/public/bundles
      - /var/www/html/vendor
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost/health.php || exit 1"]
      interval: 2s
      retries: 120
    depends_on:
      db:
        condition: service_healthy

  webpack_watcher:
    container_name: pi_webpack_watcher
    build:
      context: .
      target: pi-webpack
    command: yarn watch
    volumes:
      - ./public:/app
      # use the container's node_modules folder (don't override)
      - /app/node_modules

  docs:
    container_name: pi_docs_watcher
    build:
      context: .
      target: pi-docs
    command: sphinx-autobuild source _site/
    volumes:
      - ./docs:/app
      - ./public/docs/sphinx:/app/_site

  mail:
    container_name: pi_mail
    image: jcalonso/mailhog:v1.0.1
    ports:
      - "8025:8025"