<?php

namespace AppBundle\Repository;

/**
 * CaptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaptionRepository extends \Doctrine\ORM\EntityRepository
{
}
