<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Figuration;
use AppBundle\Entity\Video;
use Nines\UserBundle\Entity\User;

/**
 * FigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FigurationRepository extends \Doctrine\ORM\EntityRepository
{
    public function countVideos(Figuration $figuration, User $user = null) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('count(video.id)');
        $qb->from(Video::class, 'video');
        $qb->andWhere('video.figuration = :figuration');
        if( ! $user) {
            $qb->andWhere('video.hidden = 0');
        }
        $qb->setParameter('figuration', $figuration);
        return $qb->getQuery()->getSingleScalarResult();
    }
}
