<?php

namespace AppBundle\Repository;

/**
 * FigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FigurationRepository extends \Doctrine\ORM\EntityRepository
{
}
