<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Figuration;
use AppBundle\Entity\Video;

/**
 * FigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FigurationRepository extends \Doctrine\ORM\EntityRepository
{
    public function countVideos(Figuration $figuration) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('count(video.id)');
        $qb->from(Video::class, 'video');
        $qb->where('video.figuration = :figuration');
        $qb->setParameter('figuration', $figuration);
        return $qb->getQuery()->getSingleScalarResult();
    }
}
