<?php

namespace AppBundle\Repository;

/**
 * MetadataFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetadataFieldRepository extends \Doctrine\ORM\EntityRepository
{
}
