<?php

namespace AppBundle\Repository;

/**
 * MetadataElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetadataElementRepository extends \Doctrine\ORM\EntityRepository
{
}
