<?php

namespace AppBundle\Repository;

/**
 * ProfileFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileFieldRepository extends \Doctrine\ORM\EntityRepository
{
}
