<?php

namespace AppBundle\Repository;

/**
 * ScreenShotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScreenShotRepository extends \Doctrine\ORM\EntityRepository {

    public function typeaheadQuery($q) {
        $qb = $this->createQueryBuilder('e');
        $qb->andWhere("e.originalName LIKE :q");
        $qb->orderBy('e.originalName');
        $qb->setParameter('q', "{$q}%");

        return $qb->getQuery()->execute();
    }

    public function searchQuery($q) {
        $qb = $this->createQueryBuilder('e');
        $qb->addSelect("MATCH (e.originalName) AGAINST(:q BOOLEAN) as HIDDEN score");
        $qb->setParameter('q', $q);

        return $qb->getQuery();
    }
}
