<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VideoProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoProfileRepository extends EntityRepository {
    
    public function userSummary() {
        $dql = 'SELECT u, count(vp) as ct FROM AppBundle:VideoProfile vp JOIN NinesUserBundle:User u WITH vp.user = u GROUP BY vp.user';
        $query = $this->_em->createQuery($dql);
        return $query->execute();
    }

    public function videoSummary() {
        $dql = 'SELECT v, count(vp) as ct FROM AppBundle:VideoProfile vp JOIN AppBundle:Video v WITH vp.video = v GROUP BY vp.video';
        $query = $this->_em->createQuery($dql);
        return $query->execute();
    }
}
