<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Nines\UserBundle\Entity\User;

/**
 * VideoRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends EntityRepository
{
    public function typeaheadQuery($q)
    {
        $qb = $this->createQueryBuilder('e');
        $qb->andWhere("e.title LIKE :q");
        $qb->orderBy('e.title');
        $qb->setParameter('q', "%{$q}%");
        return $qb->getQuery()->execute();
    }

    public function findVideosWithoutProfile(User $user)
    {
        $subQB = $this->_em->createQueryBuilder();
        $subQB->select('IDENTITY(vp.video)');
        $subQB->from('AppBundle:VideoProfile', 'vp');
        $subQB->where('vp.user = :user');

        $qb = $this->createQueryBuilder('v');
        $qb->where($qb->expr()->notIn('v.id', $subQB->getDQL()));
        $qb->setParameter('user', $user);
        return $qb->getQuery();
    }

    public function findVideosWithProfile(User $user)
    {
        $subQB = $this->_em->createQueryBuilder();
        $subQB->select('IDENTITY(vp.video)');
        $subQB->from('AppBundle:VideoProfile', 'vp');
        $subQB->where('vp.user = :user');
        $subQB->setParameter('user', $user);

        $qb = $this->createQueryBuilder('v');
        $qb->where($qb->expr()->in('v.id', $subQB->getDQL()));
        return $qb->getQuery();
    }

}
