<?php

namespace AppBundle\Repository;

/**
 * YoutubeUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YoutubeUserRepository extends \Doctrine\ORM\EntityRepository
{
}
