<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use Nines\UserBundle\Entity\User;

/**
 * CaptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaptionRepository extends EntityRepository {

    public function findCaptionsQuery(User $user = null) {
        $qb = $this->createQueryBuilder('c');
        $qb->orderBy('c.id');
        if(!$user) {
            $qb->innerJoin('c.video', 'v');
            $qb->andWhere('v.hidden = 0');
        }
        return $qb->getQuery();
    }

}
