<?php

declare(strict_types=1);

/*
 * (c) 2020 Michael Joyce <mjoyce@sfu.ca>
 * This source file is subject to the GPL v2, bundled
 * with this source code in the file LICENSE.
 */

namespace App\Repository;

use App\Entity\Figuration;
use App\Entity\Video;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Nines\UserBundle\Entity\User;

/**
 * FigurationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FigurationRepository extends ServiceEntityRepository {
    public function countVideos(Figuration $figuration, User $user = null) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('count(video.id)');
        $qb->from(Video::class, 'video');
        $qb->andWhere('video.figuration = :figuration');
        if ( ! $user) {
            $qb->andWhere('video.hidden = 0');
        }
        $qb->setParameter('figuration', $figuration);

        return $qb->getQuery()->getSingleScalarResult();
    }
}
