<?php

namespace App\Repository;

/**
 * ProfileKeywordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileKeywordRepository extends \Doctrine\ORM\EntityRepository
{
}
