<?php

namespace App\Repository;

/**
 * ProfileElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileElementRepository extends \Doctrine\ORM\EntityRepository
{
}
