<?php

declare(strict_types=1);

namespace App\Repository;

use App\Entity\VideoProfile;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * VideoProfileRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoProfileRepository extends ServiceEntityRepository {
    public function __construct(ManagerRegistry $registry) {
        parent::__construct($registry, VideoProfile::class);
    }

    public function userSummary() {
        $dql = 'SELECT u, count(vp) as ct FROM App:VideoProfile vp JOIN NinesUserBundle:User u WITH vp.user = u GROUP BY vp.user';
        $query = $this->_em->createQuery($dql);

        return $query->execute();
    }

    public function videoSummary() {
        $dql = 'SELECT v, count(vp) as ct FROM App:VideoProfile vp JOIN App:Video v WITH vp.video = v GROUP BY vp.video';
        $query = $this->_em->createQuery($dql);

        return $query->execute();
    }
}
