<?php

namespace AppBundle\Entity;

/**
 * VideoProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoProfileRepository extends \Doctrine\ORM\EntityRepository
{
}
